> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Numpy Library for Beginners


### Five most useful functions for beginners

This notebook introduces the 5 most useful function in Data Analysis using Numpy

- np.reshape
- np.median
- np.mean
- np.split
- np.lower

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [3]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Please enter your API key ( from https://jovian.ml/ ):
API KEY: ········
[jovian] Updating notebook "cortiz/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/cortiz/numpy-array-operations


'https://jovian.ml/cortiz/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [5]:
import numpy as np

In [33]:
# List of functions explained 
# function1 = np.reshape
# fucntion2 = np.median
# function3 = np.mean
# function4 = np.split
# function5 = np.histogram

## Function 1 - np.reshape()

Gives a new shape to an array without changing its data.

In [8]:
# Example 1 - working (change this)
arr1 = [[1, 2, 4], 
        [3, 4, 6]]

np.reshape(arr1, (3,2))

array([[1, 2],
       [4, 3],
       [4, 6]])

Example 1 involves arr1 with 2 rows and 3 columns. Upon applying the desired dimension using the np.reshape function, it has now 3 rows and 2 columns.

In [10]:
# Example 2 - working
a = np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [11]:
a.reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

Second example show reshaping a that has only one row to having 4 rows with 2 columns.

In [15]:
# Example 3 - breaking (to illustrate when it breaks)
arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.reshape(arr2, (0,6))

ValueError: cannot reshape array of size 6 into shape (0,6)

Example 3 shows that we can't use 0 in reshaping an array into a new dimension.

This function is most useful when dealing with neural networks.

In [16]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "cortiz/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/cortiz/numpy-array-operations


'https://jovian.ml/cortiz/numpy-array-operations'

## Function 2 - np.median

Compute the median along the specified axis.

In [18]:
# Example 1 - working
b = np.array([[17, 2, 4], [4, 6, 18]])
np.median(b)

5.0

Example 1 shows computing the median of the values contained in an array.

In [21]:
# Example 2 - working
np.median(b, axis = 0)

array([10.5,  4. , 11. ])

Including axis = 0 computes the median in each column. Meanwhile, axis = 1 computes the median in each row.

In [25]:
# Example 3 - breaking
np.median(b, axis = 2)

AxisError: axis 2 is out of bounds for array of dimension 2

We can't use 2 as a value in the parameter 'axis'.

Median is one measures of central tendency and it is very useful in performing Data Analysis.

In [26]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "cortiz/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/cortiz/numpy-array-operations


'https://jovian.ml/cortiz/numpy-array-operations'

## Function 3 - np.mean

Compute the arithmetic mean along the specified axis.

In [28]:
# Example 1 - working
c = np.array([[1, 2, 17, 24, 10], [3, 4, 11, 16, 24]])
np.mean(c)

11.2

np.mean returns the mean of the given array.

In [29]:
# Example 2 - working
np.mean(c, axis = 1)

array([10.8, 11.6])

Adding axis = 1 in the function helps use determine the mean of each row.

In [31]:
# Example 3 - breaking (to illustrate when it breaks)
np.mean(c, axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

Again, we can't use 2 in index.

Just like median, mean is also a great function in performing Data Analysis.

In [32]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "cortiz/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/cortiz/numpy-array-operations


'https://jovian.ml/cortiz/numpy-array-operations'

## Function 4 - np.split

Split an array into multiple sub-arrays as views into ary.

In [35]:
# Example 1 - working
y = np.arange(12)
np.split(y, 4)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

y has 12 items in it. Upon applying np.split, we are able to split these 12 into 4 sub-arrays.

In [37]:
# Example 2 - working
z = np.arange(20)
np.split(z, 10)

[array([0, 1]),
 array([2, 3]),
 array([4, 5]),
 array([6, 7]),
 array([8, 9]),
 array([10, 11]),
 array([12, 13]),
 array([14, 15]),
 array([16, 17]),
 array([18, 19])]

z has 20 items in it. Upon applying np.split, we are able to split these 20 into 10 sub-arrays.

In [39]:
# Example 3 - breaking (to illustrate when it breaks)
c = np.arange(5)
np.split(c, 4)

ValueError: array split does not result in an equal division

Make sure that when applying np.split, the sub-arrays must have the same length.

In [40]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "cortiz/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/cortiz/numpy-array-operations


'https://jovian.ml/cortiz/numpy-array-operations'

## Function 5 - np.char.lower

Return an array with the elements converted to lowercase.

In [46]:
# Example 1 - working
k = np.array(['Anne','Bry', 'Cha', 'Aya', 'Bie'])
np.char.lower(k)

array(['anne', 'bry', 'cha', 'aya', 'bie'], dtype='<U4')

Using np.lower helps use convert proper case to lowercase.

In [49]:
# Example 2 - working
j = np.array(['ORTIZ', 'CATINDIG', 'LICARTE'])
np.char.lower(j)

array(['ortiz', 'catindig', 'licarte'], dtype='<U8')

Using np.lower helps use convert uppercase letters to lowercase.

In [50]:
# Example 3 - breaking (to illustrate when it breaks)
m = np.array([1, 5, 9])
np.char.lower(m)

TypeError: string operation on non-string array

Obviously, we can't use this function of integers and float.

This function is very useful specially in dealing with text data.

In [51]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "cortiz/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/cortiz/numpy-array-operations


'https://jovian.ml/cortiz/numpy-array-operations'

## Conclusion

In this notebook, you were able to have some understanding on the most useful numpy functions in performing Data Analysis using Python.

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
